---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=marvelexplorer.conf.j2 dest=/etc/init/marvelexplorer.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=marvelexplorer state=restarted
